# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    package_agent: 'https://github.com/puppetlabs/mcollective-package-agent.git'
